language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: e6l2XDD/shEg+qmgQejljdF1Ni2TY0p1Un2Ol66ORQKlYb7azDK36Hd7tjoR6c9PC/By0Qk9WweA0kjMSECE9150wzJh4TFNhcuut8YBLbEZjwZzPsFeDz5Xl1fGVfaNx+2hUqTnyllRcJTK6jii//wAeBBWN6a57W2Qbhpu++MoIAhB6dv1cGYzfBMvLBYlc0RaSsRY9lrqMxWwzvh2t3MKGAE54cwT+37GBDQvRM2NSsmcwHh6U3J4I9Vvp5JieExB7QFwpR7ZEAPppwIZ1Re8LlwkVw/2pP2ftzCstwc9MXllO92evYMiV3CnI81rr40vS8S0RKr0Rrvt3pf2yqkhqwCacDkX9Trfo2W8dtGBRjvPW22bfzWlNlFJbnYRHBhkyn+f6oaP1f4vCpTdtYyJng5VV1+NiF3a5KfZhV2u5y3moPDBm8tEpTSInorrZLH8ejBHyEaVsk9sD+13Us+rIZyQNCqi8Pv/4viHkivhcI9oIufAEE2gQOLpV2JojfoIfEGyFS6OpbFQqfx2lQuICrsasSLzLy+dEBYsIRTSVkdXSNovIphN4uLHSYlzHs307dqTolqtk/JRZXT/OaXe8uXo0ZUpfElZ8/BOzdFi1846X3q33E5JgWaWT4IEgkkmhVdXha9rUse2oIkQrgfNSdpyJcaFoe6Q09UzttE=
  app: david-scott-node-capstone
  on:
    repo: thinkful-ei17/david-scott-node-capstone
